# .github/workflows/feature_pipeline.yml
name: FeaturePipeline
env:
    NODE_ENV: production
on:
    push:
        branches: ['*', '!main']
    pull_request:
        branches: ['main']
    workflow_dispatch:
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '12.x'
                  cache: 'npm'
            - name: Install Dependencies
              run: |
                  npm ci
            - name: Run Unit Tests
              run: npm run test
    acceptance-tests:
        runs-on: ubuntu-latest
        needs: tests
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm ci
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  build: npm run build
                  start: npm start
