# .github/workflows/main.yml
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: |
          cd web && npm install
      - name: Run Unit Tests
        run: cd web && npm run test
  acceptance-tests:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd acceptance-tests && npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: cd acceptance-tests && npm run build
          start: cd acceptance-tests && npm start
  deploy:
    needs: acceptance-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: |
          cd web && npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-west-1
      - name: Deploy Next.js app
        run: cd web && npx @sls-next/serverless-patched
